server:
  port: 8761
spring:
  application:
    name: cloud-eureka-server

eureka:
  instance:
    hostname: quellanan.a
  client:
    service-url:
      defaultZone: http://quellanan.b:8762/eureka
    register-with-eureka: true
    fetch-registry: true
  dashboard:
    enabled: true