server:
  port: 8762
spring:
  application:
    name: cloud-eureka-server

eureka:
  instance:
    hostname: quellanan.b
  client:
    service-url:
      defaultZone: http://quellanan.a:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  dashboard:
    enabled: true