server:
  port: 8081
spring:
  application:
    name: service-code-hw
  redis:
    host: 127.0.0.1
    port: 6379
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://quellanan.a:8761/eureka/,http://quellanan.b:8762/eureka/
    instance:
      prefer-ip-address: true

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 3000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule


feign:
  hystrix:
    enabled: false
  compression:
  request:
    enabled: true
    mime-types: text/html,application/xml,application/json
    min-request-size: 2048
  response:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000